import {
  Home,
  Play,
  Radio,
  Music,
  Folder,
  History,
  Clock,
  ThumbsUp,
  ChevronDown,
  Coins,
  TrendingUp,
  FileText,
  Activity,
  HelpCircle,
  Upload,
  FileImage,
  Trophy,
  Shield,
  Sparkles,
  Search,
  Zap,
} from "lucide-react";

const mainNavItems = [
  { icon: FileImage, label: "Discover", href: "/" },
  { icon: Search, label: "Explore Content", href: "/explorecontent" },
  { icon: Sparkles, label: "Create Token", href: "/contentnew" },
  { icon: Zap, label: "Zora Create", href: "/zoracreate" },
  { icon: Search, label: "Zora Explore", href: "/zoraexplore" },
  { icon: Trophy, label: "Leaderboard", href: "/leaderboard" },
  { icon: Radio, label: "Create Channel", href: "/create-channel" },
  { icon: Trophy, label: "Creators", href: "/creators" },
  { icon: Radio, label: "Channels", href: "/channels" },
];