export const PUMP_FUN_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "newAddr", type: "address", internalType: "address" },
      { name: "feeAmt", type: "uint256", internalType: "uint256" },
      { name: "basisFee", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createPool",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "buy",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "maxEthCost", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "sell",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "minEthOutput", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "calculateEthCost",
    inputs: [
      {
        name: "token",
        type: "tuple",
        internalType: "struct PumpFun.Token",
        components: [
          { name: "tokenMint", type: "address", internalType: "address" },
          { name: "virtualTokenReserves", type: "uint256", internalType: "uint256" },
          { name: "virtualEthReserves", type: "uint256", internalType: "uint256" },
          { name: "realTokenReserves", type: "uint256", internalType: "uint256" },
          { name: "realEthReserves", type: "uint256", internalType: "uint256" },
          { name: "tokenTotalSupply", type: "uint256", internalType: "uint256" },
          { name: "mcapLimit", type: "uint256", internalType: "uint256" },
          { name: "complete", type: "bool", internalType: "bool" },
        ],
      },
      { name: "tokenAmount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getBondingCurve",
    inputs: [{ name: "mint", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct PumpFun.Token",
        components: [
          { name: "tokenMint", type: "address", internalType: "address" },
          { name: "virtualTokenReserves", type: "uint256", internalType: "uint256" },
          { name: "virtualEthReserves", type: "uint256", internalType: "uint256" },
          { name: "realTokenReserves", type: "uint256", internalType: "uint256" },
          { name: "realEthReserves", type: "uint256", internalType: "uint256" },
          { name: "tokenTotalSupply", type: "uint256", internalType: "uint256" },
          { name: "mcapLimit", type: "uint256", internalType: "uint256" },
          { name: "complete", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCreateFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setFeeRecipient",
    inputs: [{ name: "newAddr", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOwner",
    inputs: [{ name: "newAddr", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "CreatePool",
    inputs: [
      { name: "mint", type: "address", indexed: true, internalType: "address" },
      { name: "user", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Complete",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      { name: "mint", type: "address", indexed: true, internalType: "address" },
      { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Trade",
    inputs: [
      { name: "mint", type: "address", indexed: true, internalType: "address" },
      { name: "ethAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "tokenAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "isBuy", type: "bool", indexed: false, internalType: "bool" },
      { name: "user", type: "address", indexed: true, internalType: "address" },
      { name: "timestamp", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "virtualEthReserves", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "virtualTokenReserves", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
] as const;